### ISSUE TITLE
java.lang.NoSuchFieldError: dmax.dialog.R$id.progress

### ISSUE THREAD

**Issue by ftp27** [d-max/spots-dialog#9] opened 2015-10-01 10:09 UTC
Hello. Your library causes error:

```
    java.lang.NoSuchFieldError: dmax.dialog.R$id.progress
            at dmax.dialog.SpotsDialog.initProgress(SpotsDialog.java:76)
            at dmax.dialog.SpotsDialog.onCreate(SpotsDialog.java:49)
            at android.app.Dialog.dispatchOnCreate(Dialog.java:353)
            at android.app.Dialog.show(Dialog.java:257)
```

**Comment by d-max** [comment] 2015-10-01 17:19
Do you use proguard?

**Comment by ftp27** [comment] 2015-10-01 17:29
No.

**Comment by d-max** [comment] 2015-10-01 17:34
This is really strange. I will check it. Please, write device android version, app build tools version

**Comment by live-wire** [comment] 2015-10-07 08:22
java.lang.NoSuchFieldError: dmax.dialog.R$id.progress
            at dmax.dialog.SpotsDialog.initProgress(SpotsDialog.java:76)
            at dmax.dialog.SpotsDialog.onCreate(SpotsDialog.java:49)
            at android.app.Dialog.dispatchOnCreate(Dialog.java:353)
            at android.app.Dialog.show(Dialog.java:257) 
i didn't get it before. I suddendly started getting it today
device android version - 4.4.4
app build tools version - 21.1.2

**Comment by d-max** [comment] 2015-10-07 09:02
I can't reproduce it on android 4.4.4 with build tools 21.1.2 and spots dialog version 0.4
If you are using proguard, add these into your custom rules file:
```
-keep class dmax.dialog.** {
    *;
}
```

**Comment by d-max** [comment] 2015-10-07 09:02
May be you use progress id in your project. Please, check it out

**Comment by d-max** [comment] 2015-10-07 09:14
One more question. Can you reproduce it in 100% times ?

**Comment by live-wire** [comment] 2015-10-07 09:37
It was working fine for me till this morning. I didn't change anything. 
I am not using proguard and progress id.
//alertDialog = new SpotDialog....
I get this error on alertDialog.show();

**Comment by live-wire** [comment] 2015-10-07 09:38
Now I'm getting this error 100% times on my kitkat device :(

**Comment by d-max** [comment] 2015-10-07 09:45
Okay. Googling and Stackowerflowing made this clear.
The problem comes, when you use in project layout resource with the same name as library uses. In you case this is dialog.xml.
Do you have such layout file? Try to rename it and check this issue again.
And I will rename resoures files in library to some more complex names to avoid such overridings

**Comment by live-wire** [comment] 2015-10-07 10:11
Yeah. This was it. :smile:  Thanks Maksym and  renaming your resource files sounds like a good idea :+1:

**Comment by d-max** [comment] 2015-10-07 10:17
Great. I am happy, we have found the solution :) Version 0.6 will contain this renaming fix.

**Comment by d-max** [comment] 2015-10-07 10:18
Fixed in version 0.6

**Comment by rajesh7777** [comment] 2017-11-27 13:37
Hello, I am getting the line as follows

AlertDialog dialog=new SpotsDialog(MainActivity.this);    //error in this line as follows

Incompatible types.
Required:
android.support.v7.app.AlertDialog
Found:
dmax.dialog.SpotsDialog

**Comment by d-max** [comment] 2017-11-29 01:55
Hi. You should replace `import android.support.v7.app.AlertDialog` with `import android.app.AlertDialog`

**Closed by d-max** 2017-11-29 01:55 UTC

**Comment by TrinhDinhPhuc** [comment] 2018-01-11 03:06
thank you!

**Comment by RADS5** [comment] 2018-06-13 20:16
hellow please i am geting error at this line :
final AlertDialog waitingDialog = new SpotsDialog(this);
                    waitingDialog.show();
                    waitingDialog.setMessage("Please waiting....");
                    waitingDialog.setCancelable(false);

here is the error :
error: constructor SpotsDialog in class SpotsDialog cannot be applied to given types;
required: Context,String,int,boolean,OnCancelListener
found: MainActivity
reason: actual and formal argument lists differ in length

**Comment by saadh393** [comment] 2019-05-03 19:18
> 
> 
> Hi @rajesh7777 . You should replace `import android.support.v7.app.AlertDialog` with `import android.app.AlertDialog`

Thanks
This Helps me
Now it's working <3

**Comment by sky2dev** [comment] 2019-09-15 07:06
thanks bro
